version: "3.9"
services:
  frontend:
    tty: true
    restart: "always"
    user: vscode
    build:
      context: ./flightlog-frontend
      target: dev
    volumes:
      - ./flightlog-frontend:/src
      - /src/node_modules
    ports:
      - "8080:8080"
  api-gateway:
    tty: true
    restart: "always"
    ports:
      - "61225:61225"
    build:
      context: ./api-gateway
      target: build_base
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=flightloguser
      - AUTHENTICATION_PROVIDER=http://keycloak:8080/auth/realms/test
      - SERVICE_USERSERVICE_URL=userservice
      - SERVICE_USERSERVICE_PORT=61226
      - SERVICE_FLIGHTSERVICE_URL=http://flightservice
      - SERVICE_FLIGHTSERVICE_PORT=61227
    depends_on:
      - "userservice"
      - "database"
      - "keycloak"
    links:
      - "database"
      - "userservice"
      - "flightservice"
    volumes:
      - ./api-gateway/src:/src
  userservice:
    tty: true
    restart: "always"
    ports:
      - "61226:61226"
    links:
      - "database"
    build:
      target: build_base
      context: ./userservice
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=flightloguser
    depends_on:
      - "database"
    volumes:
      - ./userservice/src:/src
  flightservice:
    tty: true
    restart: "always"
    ports:
      - "61227:61227"
    links:
      - "database"
      - "userservice"
    build:
      target: build_base
      context: ./flightlog-flights
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=flightlogflights
      - SERVICE_USERSERVICE_URL=userservice
      - SERVICE_USERSERVICE_PORT=61226
      - SERVICE_MODE=development
    depends_on:
      - "database"
      - "userservice"
    volumes:
      - ./flightlog-flights/src:/src
  database:
    build:
      context: ./database
    restart: "always"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: flightloguser
      MYSQL_USER: flightlog
      MYSQL_PASSWORD: my-secret-pw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  keycloak_database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: keycloak_database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_IMPORT: /tmp/test.json
      KEYCLOAK_PASSWORD: admin
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    ports:
      - "8082:8080"
    volumes:
      - ./keycloak/test.json:/tmp/test.json
    depends_on:
      - keycloak_database
  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8083:8083"
      - "8084:8084"
    depends_on:
      - "api-gateway"
