version: "3.9"
services:
  frontend:
    tty: true
    restart: "always"
    user: vscode
    build:
      context: ./flightlog-frontend
      target: dev
    volumes:
      - ./flightlog-frontend:/src:z
      - /src/node_modules:z
    ports:
      - "8080:8080"
  api-gateway:
    tty: true
    restart: "always"
    ports:
      - "61225:61225"
    build:
      context: ./api-gateway
      target: build_base
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=flightloguser
      - AUTHENTICATION_PROVIDER=http://keycloak:8080/auth/realms/test
      - SERVICE_USERSERVICE_URL=userservice
      - SERVICE_USERSERVICE_PORT=61226
      - SERVICE_FLIGHTSERVICE_URL=http://flightservice
      - SERVICE_FLIGHTSERVICE_PORT=61227
    depends_on:
      - "userservice"
      - "database"
      - "keycloak"
    links:
      - "database"
      - "userservice"
      - "flightservice"
    volumes:
      - ./api-gateway/src:/src:z
  userservice:
    tty: true
    restart: "always"
    ports:
      - "61226:61226"
    links:
      - "database"
    build:
      target: build_base
      context: ./userservice
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=flightloguser
    depends_on:
      - "database"
    volumes:
      - ./userservice/src:/src:z
  flightservice:
    tty: true
    restart: "always"
    ports:
      - "61227:61227"
    links:
      - "database"
      - "userservice"
    build:
      target: build_base
      context: ./flightlog-flights
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=flightlogflights
      - SERVICE_USERSERVICE_URL=userservice
      - SERVICE_USERSERVICE_PORT=61226
      - SERVICE_MODE=development
    depends_on:
      - "database"
      - "userservice"
    volumes:
      - ./flightlog-flights/src:/src:z
  database:
    build:
      context: ./database
    restart: "always"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: flightloguser
      MYSQL_USER: flightlog
      MYSQL_PASSWORD: my-secret-pw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  keycloak_database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
  keycloak:
    build:
      context: ./keycloak
    ports:
      - "8082:8080"
    volumes:
      - ./keycloak/test.json:/tmp/test.json:z
      - ./keycloak/compose-start.sh:/opt/keycloak/bin/compose-start.sh:z
  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:z
    ports:
      - "8083:8083"
      - "8084:8084"
    depends_on:
      - "api-gateway"
