version: "3.9"
services:
  frontend:
    tty: true
    user: vscode
    build:
      context: ./flightlog-frontend
      target: dev
    volumes:
      - ./flightlog-frontend:/src
      - /src/node_modules
    ports:
      - "8080:8080"
  api-gateway:
    tty: true
    ports:
      - "61225:61225"
    build:
      context: ./api-gateway
      target: build_base
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=flightloguser
      - SERVICE_USERSERVICE_URL=userservice
      - SERVICE_USERSERVICE_PORT=61226
      - SERVICE_FLIGHTSERVICE_URL=http://flightservice
      - SERVICE_FLIGHTSERVICE_PORT=61227
    depends_on:
      - "userservice"
      - "database"
    links:
      - "database"
      - "userservice"
      - "flightservice"
    volumes:
      - ./api-gateway/src:/src
  userservice:
    tty: true
    ports:
      - "61226:61226"
    links:
      - "database"
    build:
      target: build_base
      context: ./userservice
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=flightloguser
    depends_on:
      - "database"
    volumes:
      - ./userservice/src:/src
  flightservice:
    tty: true
    ports:
      - "61227:61227"
    links:
      - "database"
      - "userservice"
    build:
      target: build_base
      context: ./flightlog-flights
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=flightlogflights
      - SERVICE_USERSERVICE_URL=userservice
      - SERVICE_USERSERVICE_PORT=61226
      - SERVICE_MODE=development
    depends_on:
      - "database"
      - "userservice"
    volumes:
      - ./flightlog-flights/src:/src
  database:
    build:
      context: ./database
    restart: "always"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: flightloguser
      MYSQL_USER: flightlog
      MYSQL_PASSWORD: my-secret-pw

  casdoor:
    image: casbin/casdoor
    depends_on:
      - database
    volumes:
      - ./conf:/conf/
    ports:
      - "8000:8000"
